drop table if exists item_requests cascade;
drop table if exists comments cascade;
drop table if exists bookings cascade;
drop table if exists items cascade;
drop table if exists users cascade;

CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    email   VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS item_requests
(
    request_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR,
    requestor   BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    created     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_item_request PRIMARY KEY (request_id)
);

CREATE TABLE IF NOT EXISTS items
(
    item_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    available   BOOLEAN,
    owner_id    BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    request_id  BIGINT NULL REFERENCES item_requests (request_id) ON DELETE CASCADE,
    CONSTRAINT pk_item PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date   TIMESTAMP WITHOUT TIME ZONE,
    item_id    BIGINT REFERENCES items (item_id) ON DELETE CASCADE,
    booker_id  BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    status     VARCHAR,
    CONSTRAINT pk_booking PRIMARY KEY (booking_id)
);

CREATE TABLE IF NOT EXISTS comments
(
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text       VARCHAR,
    item_id    BIGINT REFERENCES items (item_id) ON DELETE CASCADE,
    author_id  BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    created    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_comment PRIMARY KEY (comment_id)
);